- rule:
  - ID: AWS-001
    Title: Ensure S3 Buckets Are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets are not publicly accessible.
      Public access to S3 buckets can lead to data exposure and potential data breaches,
      as unauthorized users may be able to view or download sensitive information.
    Rationale: Preventing public access to S3 buckets is crucial for maintaining data
      confidentiality and integrity. Publicly accessible buckets can be exploited
      by malicious actors, leading to data leaks, regulatory non-compliance, and reputational
      damage.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket list and check the 'Access' column for any buckets marked
      as 'Public'.
    - For each bucket, click on the bucket name, go to the 'Permissions' tab, and
      ensure that 'Block all public access' is enabled.
    Default Value: By default, S3 buckets block all public access unless explicitly
      configured otherwise.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service and select the affected bucket.
    - Go to the 'Permissions' tab.
    - Enable 'Block all public access' settings.
    - Review and update bucket policies and access control lists (ACLs) to remove
      any public permissions.
