- rule:
  - ID: AWS-BP-001
    Title: Enable Multi-Factor Authentication (MFA) on Root Account
    Profile Applicability: Level 1
    Description: Ensure that MFA is enabled on the AWS root account to add an additional
      layer of security. MFA requires users to provide not only a password or access
      key, but also a second form of authentication, such as a code from a mobile
      device.
    Rationale: Enabling MFA on the root account helps protect against unauthorized
      access. The root account has full access to all resources in the AWS account,
      and if compromised, could lead to severe security breaches and data loss.
    Audit:
    - Sign in to the AWS Management Console.
    - Navigate to the IAM dashboard.
    - Check the Security Status section for the status of MFA on the root account.
    - Verify that MFA is enabled for the root account.
    Default Value: MFA is not enabled by default on the root account.
    Remediation:
    - Sign in to the AWS Management Console.
    - Go to the IAM dashboard and select the root account.
    - Follow the prompts to enable MFA, choosing either a virtual or hardware MFA
      device.
    - Complete the MFA setup process as instructed.
