- rule:
    ID: AWS-IAM-01
    Title: Ensure IAM Users Have MFA Enabled
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that all IAM users in the AWS account have multi-factor
      authentication (MFA) enabled to enhance security by requiring an additional
      verification method.
    Rationale: Enabling MFA for IAM users adds an extra layer of security to protect
      against unauthorized access. Without MFA, users are more susceptible to attacks,
      such as phishing, which can lead to compromised credentials and unauthorized
      access to AWS resources.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM Dashboard.
    - Select Users from the navigation pane.
    - For each user, check the Security Credentials tab to verify if MFA is enabled.
    - Alternatively, use the AWS CLI command aws iam list-virtual-mfa-devices to list
      users without MFA.
    Default Value: By default, IAM users are created without MFA enabled.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM Dashboard.
    - Select Users from the navigation pane.
    - Choose the user for whom you want to enable MFA.
    - Go to the Security Credentials tab and select Manage MFA.
    - Follow the prompts to enable and configure MFA for the user.
