- rule:
  - ID: AWS-S3-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible
      to prevent unauthorized access to sensitive data stored within the buckets.
    Rationale: Publicly accessible S3 buckets can lead to data breaches, as unauthorized
      users may gain access to sensitive information. Ensuring that S3 buckets are
      private protects data confidentiality and integrity.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the list of buckets and check the Access column for any buckets marked
      as "Public".
    - For each bucket, click on the bucket name.
    - Go to the Permissions tab and review the Block Public Access settings.
    - Confirm that the "Block all public access" option is enabled.
    Default Value: By default, S3 buckets are private and not publicly accessible.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service and select the bucket that is publicly accessible.
    - Go to the Permissions tab.
    - Enable the "Block all public access" option.
    - Save the changes to ensure the bucket is no longer publicly accessible.
