- rule:
  - ID: AWS-BP-001
    Title: Ensure AWS S3 Buckets are Private
    Profile Applicability: Level 1
    Description: This check ensures that all Amazon S3 buckets are set to private
      to prevent unauthorized access to sensitive data. S3 buckets should not be publicly
      accessible unless explicitly required and properly secured.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      access to sensitive information. Ensuring buckets are private mitigates these
      risks by restricting access to only authorized users.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the permissions and ensure that 'Block all public access'
      is enabled.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to verify
      that the bucket's ACL settings do not allow public access.
    Default Value: By default, newly created S3 buckets are private.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that needs to be set to private.
    - Go to the 'Permissions' tab and ensure 'Block all public access' is enabled.
    - Review and update the bucket policy and ACL to remove any public access permissions.
