- rule:
  - ID: AWS-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible
      unless explicitly required. Publicly accessible buckets can expose sensitive
      data to unauthorized users.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      access to sensitive information. Ensuring buckets are private by default reduces
      the risk of data exposure.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the "Permissions" tab.
    - Ensure that the bucket does not have a public access configuration.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> and
      verify that the ACL does not grant public access.
    Default Value: S3 buckets are private by default.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the "Permissions" tab and adjust the settings to remove public access.
    - Consider using bucket policies or access control lists (ACLs) to restrict access
      further.
