- rule:
    ID: AWS-BP-001
    Title: Ensure Multi-Factor Authentication (MFA) is enabled for all IAM users
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that MFA is enabled for all IAM users to provide
      an additional layer of security. MFA requires users to present two or more separate
      forms of identification before they can access AWS resources.
    Rationale: Enabling MFA for IAM users helps protect AWS accounts from unauthorized
      access. Without MFA, if a user's password is compromised, an attacker can gain
      full access to the account. MFA mitigates this risk by requiring a second form
      of verification.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - In the navigation pane, choose 'Users'.
    - Select each user and check if MFA is enabled by looking for 'MFA Device' in
      the 'Security Credentials' tab.
    Default Value: MFA is not enabled for IAM users by default.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - In the navigation pane, choose 'Users'.
    - Select the user for whom you want to enable MFA.
    - Go to the 'Security Credentials' tab and click on 'Manage MFA Device'.
    - Follow the instructions to enable and configure an MFA device for the user.
