- rule:
  - ID: AWS-001
    Title: Enable Multi-Factor Authentication (MFA) for IAM Users
    Profile Applicability: Level 1
    Description: Ensure that all IAM users have Multi-Factor Authentication (MFA)
      enabled to enhance security by requiring an additional verification step during
      sign-in.
    Rationale: Enabling MFA adds an extra layer of security to user accounts by requiring
      a second form of authentication. This reduces the risk of unauthorized access
      in case user credentials are compromised.
    Audit:
    - Step 1: Sign in to the AWS Management Console.
    - Step 2: Navigate to the IAM service.
    - Step 3: In the navigation pane, choose Users.
    - Step 4: Verify that MFA is enabled for each user by checking the MFA column.
    - Step 5: Alternatively, use the AWS CLI command 'aws iam list-virtual-mfa-devices'
        to list users and their MFA status.
    Default Value: By default, IAM users do not have MFA enabled.
    Remediation:
    - Step 1: Sign in to the AWS Management Console.
    - Step 2: Navigate to the IAM service.
    - Step 3: In the navigation pane, choose Users and select the user for whom you
        want to enable MFA.
    - Step 4: Choose the Security credentials tab.
    - Step 5: In the Multi-factor authentication section, choose Assign MFA device.
    - Step 6: Follow the instructions to assign and activate an MFA device for the
        user.
