- rule:
    ID: application-signals
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets do not allow public access.
      Publicly accessible S3 buckets can lead to unauthorized data access and potential
      data breaches.
    Rationale: Restricting public access to S3 buckets helps protect sensitive data
      from unauthorized access and reduces the risk of data leaks. If buckets are
      publicly accessible, anyone on the internet can access the data, leading to
      potential security and compliance issues.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the bucket permissions.
    - Verify that the bucket policy does not grant public read or write access.
    - Check the Block Public Access settings for each bucket and ensure they are enabled.
    Default Value: By default, new S3 buckets do not allow public access unless explicitly
      configured otherwise.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service and select the affected bucket.
    - Review and edit the bucket policy to remove any public access permissions.
    - Enable Block Public Access settings for the bucket to prevent future public
      access configurations.
