- rule:
  - ID: application-signals
    Title: Ensure S3 Buckets are Private
    Profile Applicability: Level 1
    Description: This check ensures that all Amazon S3 buckets are set to private,
      preventing unauthorized public access. S3 buckets should have appropriate permissions
      that restrict access to only authorized users and services.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      access to sensitive information. Ensuring buckets are private mitigates the
      risk of exposing data to the internet.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, review the bucket permissions.
    - Verify that the bucket policy and access control list (ACL) do not allow public
      access.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to check
      ACL settings.
    - Use the AWS CLI command aws s3api get-bucket-policy --bucket <bucket-name> to
      review bucket policies.
    Default Value: By default, newly created S3 buckets are private and do not allow
      public access.
    Remediation:
    - If a bucket is found to be public, update the bucket policy and ACL to restrict
      access.
    - Remove any public access blocks and reconfigure settings to ensure only authorized
      users can access the bucket.
    - Utilize AWS S3 Block Public Access settings to prevent public access at the
      account level.
