- rule:
    ID: application-signals
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets are not publicly accessible.
      Public access to S3 buckets can lead to unintended data exposure and potential
      data breaches.
    Rationale: Preventing public access to S3 buckets is crucial to protect sensitive
      data from unauthorized access. Publicly accessible buckets can expose sensitive
      information and lead to compliance violations and data breaches.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the "Permissions" tab.
    - Ensure that "Block all public access" is enabled.
    - Verify that there are no bucket policies or ACLs granting public access.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Go to the "Permissions" tab and enable "Block all public access."
    - Review and modify bucket policies and ACLs to remove any public access permissions.
