- rule:
  - ID: application-signals
  - Title: Ensure S3 Buckets are Not Publicly Accessible
  - Profile Applicability: Level 1
  - Description: This check ensures that Amazon S3 buckets are not publicly accessible.
      Publicly accessible buckets can expose sensitive data to unauthorized users.
  - Rationale: Publicly accessible S3 buckets can lead to data breaches, unauthorized
      access, and data leaks. Ensuring buckets are private mitigates these risks by
      restricting access to only authorized users.
  - Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Review the list of buckets and check the Access column for any buckets marked
      as Public.
    - For each bucket, click on the bucket name, go to the Permissions tab, and verify
      that the bucket policy and access control list (ACL) do not allow public access.
  - Default Value: By default, S3 buckets are private and not publicly accessible.
  - Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Select the publicly accessible bucket.
    - Go to the Permissions tab and modify the bucket policy and ACL to remove public
      access.
    - Consider enabling block public access settings to prevent future public access
      configurations.
