- rule:
  - ID: application-signals
    Title: Ensure Multi-Factor Authentication (MFA) is enabled for all IAM users
    Profile Applicability: Level 1
    Description: This check ensures that Multi-Factor Authentication (MFA) is enabled
      for all AWS Identity and Access Management (IAM) users to add an extra layer
      of security. MFA requires users to provide two or more verification factors
      to gain access to AWS resources.
    Rationale: Enabling MFA for IAM users protects AWS accounts by requiring additional
      verification, reducing the risk of compromised credentials. Without MFA, users
      are only protected by their passwords, which can be vulnerable to attacks such
      as phishing or brute force.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - In the navigation pane, select 'Users'.
    - For each user, check if MFA is enabled by looking for the "MFA" column in the
      user list.
    - Alternatively, use the AWS CLI command aws iam list-virtual-mfa-devices to list
      users with MFA enabled.
    Default Value: By default, IAM users do not have MFA enabled.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - In the navigation pane, select 'Users'.
    - Select a user and go to the 'Security credentials' tab.
    - Under 'Assigned MFA device', choose 'Manage'.
    - Follow the prompts to assign a virtual or hardware MFA device to the user.
