- rule:
    ID: application-signals
    Title: Ensure AWS S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that AWS S3 buckets do not allow public access.
      Publicly accessible S3 buckets can lead to unauthorized data exposure and potential
      data breaches.
    Rationale: Public access to S3 buckets can lead to sensitive data exposure, unauthorized
      data modifications, and compliance violations. Restricting public access helps
      to safeguard data and maintain compliance with security standards.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Review the permissions settings for each bucket.
    - Verify that 'Block all public access' is enabled for each bucket.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to check
      the bucket ACL settings and ensure no public access is granted.
    Default Value: By default, new S3 buckets block all public access.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the 'Permissions' tab.
    - Enable 'Block all public access'.
    - Review and adjust bucket policies and ACLs to ensure no public access is granted.
