- rule:
    ID: AWS-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible,
      which can prevent unauthorized access to sensitive data stored in S3. Publicly
      accessible buckets can be accessed by anyone on the internet, leading to potential
      data breaches.
    Rationale: Ensuring that S3 buckets are not publicly accessible mitigates the
      risk of unauthorized data access and potential data leaks. Publicly accessible
      buckets can expose sensitive information to malicious actors, leading to data
      breaches and compliance violations.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Review the permissions of each bucket.
    - Check the bucket policy and access control list (ACL) settings to ensure that
      they do not allow public access.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to verify
      the ACL settings.
    - Use the AWS CLI command aws s3api get-bucket-policy --bucket <bucket-name> to
      review the bucket policy.
    Default Value: By default, S3 buckets are not publicly accessible unless explicitly
      configured.
    Remediation:
    - If a bucket is found to be publicly accessible, remove the public access permissions
      from the bucket policy and ACL.
    - Implement bucket policies that explicitly deny public access.
    - Enable the "Block Public Access" settings for all S3 buckets.
