- rule:
    ID: application-signals
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that S3 buckets are configured to prevent public
      access. Public access to S3 buckets can lead to data exposure and unauthorized
      access to sensitive information.
    Rationale: Preventing public access to S3 buckets is crucial to protect data from
      unauthorized access and potential breaches. Misconfigured S3 buckets can lead
      to data leaks and compliance violations.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the access permissions for each bucket.
    - Ensure that 'Block all public access' is enabled for each bucket.
    Default Value: By default, S3 buckets are private, but configurations can be changed
      to allow public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the 'Permissions' tab.
    - Enable 'Block all public access' to prevent public access to the bucket.
