- rule:
  - ID: AWS-S3-01
  - Title: Ensure S3 buckets are not publicly accessible
  - Profile Applicability: Level 1
  - Description: Check that Amazon S3 buckets are not publicly accessible to ensure
      sensitive data is not exposed to the internet.
  - Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      access to sensitive information. Ensuring that S3 buckets are not publicly accessible
      reduces the risk of data exposure.
  - Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the bucket permissions and access control lists (ACLs).
    - Verify that the bucket policy does not allow public access.
    - Use AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to review
      bucket ACL.
    - Use AWS CLI command aws s3api get-bucket-policy --bucket <bucket-name> to review
      bucket policy.
  - Default Value: By default, S3 buckets are private and not publicly accessible.
  - Remediation:
    - Remove any public access permissions from the bucket policy and ACLs.
    - Use the AWS Management Console or CLI to modify the bucket policy to restrict
      access.
    - Enable S3 Block Public Access settings to prevent future public access configurations.
