- rule:
  - ID: AWS-EC2-001
  - Title: Ensure EC2 Instances Are Using Approved AMIs
  - Profile Applicability: Level 1, Level 2
  - Description: Verify that all EC2 instances are launched using Amazon Machine Images
      (AMIs) that are approved by your organization to ensure security and compliance
      standards are met.
  - Rationale: Using unapproved AMIs can introduce vulnerabilities and non-compliance
      issues, as they might contain outdated software or insecure configurations.
      Approved AMIs are vetted for security and compliance, reducing the risk of exposure
      to threats.
  - Audit: 1. Log in to the AWS Management Console. 2. Navigate to the EC2 Dashboard.
      3. List all running instances and note their AMI IDs. 4. Cross-reference the
      AMI IDs with the list of approved AMIs maintained by your organization. 5. Ensure
      all instances are using AMIs from the approved list.
  - Default Value: By default, there is no restriction on the AMIs that can be used
      for launching EC2 instances.
  - Remediation: 1. Identify instances using unapproved AMIs. 2. Create snapshots
      of the instance volumes for backup. 3. Launch new instances using approved AMIs.
      4. Migrate data from the old instances to the new ones. 5. Terminate the instances
      that were using unapproved AMIs.
