- rule:
    ID: AWS-S3-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This security check ensures that Amazon S3 buckets are configured
      to prevent public access. Publicly accessible buckets can expose sensitive data
      to unauthorized users, potentially leading to data breaches.
    Rationale: Preventing public access to S3 buckets is crucial to protect sensitive
      data from unauthorized exposure. Publicly accessible buckets can be exploited
      by attackers to gain access to confidential information, leading to data breaches
      and compliance violations.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select each bucket and check the permissions tab.
    - Verify that the bucket does not have any public access permissions set.
    - Use the AWS CLI command aws s3api get-bucket-acl to programmatically check the
      ACL settings of each bucket.
    - Use the AWS CLI command aws s3api get-bucket-policy-status to verify the bucket
      policy status.
    Default Value: By default, S3 buckets do not allow public access unless explicitly
      configured otherwise.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Go to the permissions tab and remove any public access permissions.
    - Update the bucket policy to ensure it does not allow public access.
    - Use the AWS CLI to remove any public access settings with aws s3api put-bucket-acl
      and aws s3api delete-bucket-policy as necessary.
