- rule:
  - ID: AWS-001
    Title: Ensure S3 Buckets are not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check verifies that Amazon S3 buckets do not allow public access.
      Publicly accessible S3 buckets can lead to data exposure and unauthorized access
      to sensitive information.
    Rationale: Publicly accessible S3 buckets can be exploited by unauthorized users,
      leading to data breaches and potential loss of sensitive data. Ensuring that
      S3 buckets are not publicly accessible helps protect data integrity and confidentiality.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket permissions for each bucket.
    - Ensure that the bucket policy and access control list (ACL) do not allow public
      access.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to verify
      the ACL settings.
    - Use the AWS CLI command aws s3api get-bucket-policy --bucket <bucket-name> to
      check the bucket policy.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Modify the bucket policy and ACL to remove public access permissions.
    - Enable the "Block Public Access" setting for the bucket to prevent future public
      access.
