- rule:
    ID: AWS-001
    Title: Enable Multi-Factor Authentication (MFA) for AWS Root Account
    Profile Applicability: Level 1, Level 2
    Description: Ensure that Multi-Factor Authentication (MFA) is enabled for the
      AWS root account to add an extra layer of security. MFA requires users to present
      two or more separate forms of identification before gaining access, significantly
      reducing the risk of unauthorized access.
    Rationale: Enabling MFA for the root account helps protect against security breaches
      that could result from compromised credentials. Without MFA, a malicious actor
      with access to the root account credentials could potentially have unrestricted
      access to all resources and data in the AWS account, leading to data loss, service
      disruption, or financial loss.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the IAM dashboard.
    - Check the security status section to verify if MFA is enabled for the root account.
    - Alternatively, use the AWS CLI command aws iam get-account-summary and check
      the output for the AccountMFAEnabled attribute to ensure it is set to true.
    Default Value: MFA is not enabled by default for the AWS root account.
    Remediation:
    - Log into the AWS Management Console as the root user.
    - Navigate to the IAM dashboard.
    - In the security status section, click on 'Activate MFA on your root account'.
    - Follow the prompts to select the MFA device type and complete the setup process.
