- rule:
  - ID: discovery
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible
      to prevent unauthorized access to sensitive data.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and exposure
      of sensitive information. Restricting access reduces the risk of unauthorized
      data access.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the 'Permissions' tab.
    - Ensure that the bucket policy does not allow public access.
    - Verify that the 'Block Public Access' settings are enabled.
    Default Value: By default, S3 buckets are private, and public access is blocked.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the 'Permissions' tab and review the bucket policy.
    - Remove any statements that allow public access.
    - Enable 'Block Public Access' settings for the bucket.
