- rule:
    ID: discovery
    Title: Enable Multi-Factor Authentication (MFA) for All IAM Users
    Profile Applicability: Level 1
    Description: Ensure that Multi-Factor Authentication (MFA) is enabled for all
      AWS Identity and Access Management (IAM) users to add an extra layer of security.
      MFA requires users to provide a second authentication factor in addition to
      their password, reducing the risk of compromised credentials.
    Rationale: Enabling MFA enhances security by requiring a second form of verification,
      which helps protect accounts from unauthorized access. Without MFA, accounts
      are more vulnerable to attacks such as phishing or credential stuffing.
    Audit:
    - Sign in to the AWS Management Console.
    - Navigate to the IAM Dashboard.
    - Select 'Users' from the navigation pane.
    - For each user, check the 'MFA' column to verify if MFA is enabled.
    Default Value: By default, MFA is not enabled for IAM users.
    Remediation:
    - Sign in to the AWS Management Console.
    - Navigate to the IAM Dashboard.
    - Select 'Users' from the navigation pane.
    - Choose the IAM user for whom you want to enable MFA.
    - Select the 'Security credentials' tab.
    - In the 'Multi-factor Authentication (MFA)' section, choose 'Assign MFA device.'
    - Follow the instructions to assign a virtual MFA device or hardware MFA device
      to the user.
