- rule:
  - ID: discovery
    Title: Enable Multi-Factor Authentication (MFA) for IAM Users
    Profile Applicability: Level 1, Level 2
    Description: Ensure that MFA is enabled for all IAM users with console access
      to enhance security by requiring a second form of authentication.
    Rationale: Enabling MFA helps protect user credentials from being compromised.
      Without MFA, if a user's password is exposed, the account can be easily accessed
      by unauthorized parties, leading to potential data breaches and unauthorized
      access to AWS resources.
    Audit: 1. Sign in to the AWS Management Console. 2. Navigate to the IAM dashboard.
      3. In the navigation pane, select 'Users'. 4. For each user, check the 'Security
      credentials' tab to verify if MFA is enabled. 5. If MFA is not enabled for any
      user, note the non-compliance.
    Default Value: By default, MFA is not enabled for IAM users.
    Remediation: 1. Sign in to the AWS Management Console. 2. Navigate to the IAM
      dashboard. 3. In the navigation pane, select 'Users'. 4. Choose the user for
      whom you want to enable MFA. 5. In the 'Security credentials' tab, select 'Manage
      MFA'. 6. Follow the prompts to enable and configure MFA for the user.
