- rule:
  - ID: discovery
  - Title: Ensure S3 Buckets Have Versioning Enabled
  - Profile Applicability: Level 1
  - Description: This check ensures that versioning is enabled on all Amazon S3 buckets
      to protect against accidental or malicious data deletion and to preserve, retrieve,
      and restore every version of every object stored in an S3 bucket.
  - Rationale: Enabling versioning in S3 buckets is crucial for data protection as
      it allows the recovery of objects that are accidentally deleted or overwritten.
      Without versioning, data loss can occur, leading to potential business disruptions
      and non-compliance with data retention policies.
  - Audit: 1. Sign in to the AWS Management Console. 2. Open the Amazon S3 console.
      3. In the Buckets list, select the name of the bucket you want to check. 4.
      Choose the Properties tab. 5. Under the Versioning section, verify that the
      status is Enabled.
  - Default Value: By default, S3 buckets have versioning disabled.
  - Remediation: 1. Sign in to the AWS Management Console. 2. Open the Amazon S3 console.
      3. In the Buckets list, select the name of the bucket you want to modify. 4.
      Choose the Properties tab. 5. Under the Versioning section, choose Edit. 6.
      Select Enable, then save the changes to enable versioning.
