- rule:
  - ID: AWS-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets do not allow public read
      or write access. Publicly accessible buckets can lead to data breaches and unauthorized
      data access.
    Rationale: Restricting public access to S3 buckets is crucial to prevent unauthorized
      data exposure and potential data breaches. Public access can lead to sensitive
      data being accessed or modified by unauthorized users.
    Audit: 1. Log in to the AWS Management Console. 2. Navigate to the S3 service.
      3. For each bucket, check the 'Permissions' tab. 4. Verify that the bucket policy
      and access control list (ACL) do not allow public access. 5. Use the AWS CLI
      command aws s3api get-bucket-acl --bucket <bucket-name> to programmatically
      check the ACL. 6. Use the AWS CLI command aws s3api get-bucket-policy --bucket
      <bucket-name> to review the bucket policy.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation: 1. Remove any public access granted via bucket policy or ACL. 2.
      Use the 'Block Public Access' settings in the S3 console to prevent public access.
      3. Regularly review bucket permissions to ensure compliance.
