- rule:
  - ID: AWS-IAM-001
    Title: Ensure IAM Password Policy is Enabled
    Profile Applicability: Level 1
    Description: Ensure that a strong password policy is enabled for AWS IAM users
      to enhance security by enforcing password complexity and expiration.
    Rationale: A strong password policy reduces the risk of unauthorized access by
      enforcing the use of complex passwords that are difficult to guess or crack.
      Without a strong password policy, accounts are vulnerable to brute force attacks
      and unauthorized access.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - In the left navigation pane, click on 'Account settings'.
    - Check the password policy settings to ensure they meet the organization's security
      requirements, such as minimum password length, requiring at least one uppercase
      letter, one lowercase letter, one number, and one non-alphanumeric character,
      and password expiration.
    Default Value: By default, AWS does not enforce a password policy.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - In the left navigation pane, click on 'Account settings'.
    - Click on 'Change' next to 'Password policy'.
    - Configure the password policy to meet security requirements, including setting
      a minimum password length and requiring complexity requirements.
    - Save the changes.
