- rule:
    ID: discovery
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets do not allow public access.
      Publicly accessible buckets can expose sensitive data and lead to data breaches.
    Rationale: Preventing public access to S3 buckets is crucial to protect sensitive
      data from unauthorized users. Public buckets can lead to data leaks and non-compliance
      with data protection regulations.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select each bucket and click on the "Permissions" tab.
    - Check the "Block public access" settings to ensure all options are enabled.
    Default Value: By default, new S3 buckets have all public access blocked.
    Remediation:
    - Go to the S3 service in the AWS Management Console.
    - Select the bucket with public access.
    - Click on the "Permissions" tab and then "Block public access."
    - Enable all options to block public access and save changes.
