- rule:
    ID: discovery
    Title: Ensure Multi-Factor Authentication (MFA) is enabled for all IAM users
    Profile Applicability: Level 1
    Description: MFA adds an extra layer of security by requiring users to provide
      not only a password but also a second form of authentication. This reduces the
      risk of compromised credentials.
    Rationale: Enabling MFA for IAM users is critical in preventing unauthorized access
      to AWS resources. Without MFA, if a password is compromised, an attacker could
      gain full access to the account.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select Users from the navigation pane.
    - Check each user to ensure that MFA is enabled.
    - Alternatively, use the AWS CLI command aws iam list-virtual-mfa-devices to list
      users with MFA enabled.
    Default Value: By default, MFA is not enabled for IAM users.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select Users from the navigation pane.
    - Choose the user for whom you want to enable MFA.
    - Select the Security credentials tab.
    - Under Multi-factor Authentication (MFA), choose Assign MFA device.
    - Follow the prompts to assign a virtual or hardware MFA device to the user.
