- rule:
    ID: AWS-S3-001
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets do not allow public access.
      Public access to S3 buckets can lead to unauthorized data exposure and potential
      data breaches.
    Rationale: Publicly accessible S3 buckets can expose sensitive data to the internet,
      leading to data leaks and security incidents. Ensuring buckets are not publicly
      accessible reduces the risk of unauthorized access.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the permissions for each bucket.
    - Check the bucket policy and access control list (ACL) to ensure they do not
      allow public access.
    - Verify that the 'Block all public access' setting is enabled.
    Default Value: By default, S3 buckets do not allow public access unless explicitly
      configured.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Update the bucket policy and ACL to remove any public access permissions.
    - Enable the 'Block all public access' setting for the bucket.
