- rule:
    ID: appconfig
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets do not allow public access.
      Publicly accessible S3 buckets can expose sensitive data to unauthorized users,
      leading to potential data breaches and compliance violations.
    Rationale: Publicly accessible S3 buckets can be exploited by malicious actors
      to access or manipulate sensitive data. Ensuring that S3 buckets are not publicly
      accessible reduces the risk of data leaks and enhances security posture.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select a bucket and check its permissions.
    - Verify that the bucket policy and access control list (ACL) do not allow public
      access.
    - Confirm that the "Block Public Access" setting is enabled.
    Default Value: By default, S3 buckets are created with public access blocked.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Edit the bucket policy and ACL to remove public access permissions.
    - Enable "Block Public Access" for the bucket.
    - Save the changes and verify the bucket is no longer publicly accessible.
