- rule:
  - ID: AWS-001
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible,
      which can help prevent unauthorized access to sensitive data stored in the cloud.
      Public access to S3 buckets should be restricted to prevent data breaches and
      ensure compliance with data protection regulations.
    Rationale: Publicly accessible S3 buckets can lead to data exposure, unauthorized
      data access, and potential data breaches. By restricting public access, organizations
      can mitigate the risk of sensitive data being accessed by unauthorized users,
      thus maintaining data confidentiality and integrity.
    Audit:
    - Step 1: Log in to the AWS Management Console.
    - Step 2: Navigate to the S3 service.
    - Step 3: Select the bucket you want to check.
    - Step 4: Go to the "Permissions" tab.
    - Step 5: Verify that the "Block public access" settings are enabled.
    - Step 6: Check the bucket policy and access control list (ACL) to ensure there
        are no public permissions.
    Default Value: By default, S3 buckets are private and not publicly accessible.
    Remediation:
    - Step 1: Log in to the AWS Management Console.
    - Step 2: Navigate to the S3 service.
    - Step 3: Select the non-compliant bucket.
    - Step 4: Go to the "Permissions" tab.
    - Step 5: Enable "Block public access" settings.
    - Step 6: Review and update the bucket policy and ACL to remove any public permissions.
