- rule:
    ID: appconfig
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible.
      Public access to S3 buckets can lead to data exposure and potential breaches,
      as unauthorized users may be able to view or download sensitive information.
    Rationale: Preventing public access to S3 buckets is crucial for maintaining data
      privacy and security. Publicly accessible buckets can lead to unauthorized access
      and data leaks, resulting in compliance violations and reputational damage.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the "Permissions" tab.
    - Verify that "Block all public access" settings are enabled.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to ensure
      no public access is granted.
    Default Value: By default, new S3 buckets block all public access.
    Remediation:
    - Navigate to the S3 service in the AWS Management Console.
    - Select the bucket that is publicly accessible.
    - Go to the "Permissions" tab.
    - Enable the "Block all public access" settings.
    - Review and remove any bucket policies or ACLs that grant public access.
