- rule:
    ID: appconfig
    Title: Ensure Multi-Factor Authentication (MFA) is enabled for all IAM users
    Profile Applicability: Level 1, Level 2
    Description: Multi-Factor Authentication (MFA) adds an extra layer of security
      to your AWS account by requiring not only a password and username but also something
      that only the user has on them, i.e., a piece of information only they should
      know or have immediately to hand - such as a physical token.
    Rationale: Enabling MFA for IAM users reduces the risk of compromised credentials
      and unauthorized access to your AWS environment. Without MFA, an attacker who
      obtains a user's password could gain full access to your AWS resources and data.
    Audit: 1. Sign in to the AWS Management Console. 2. Navigate to the IAM service.
      3. In the navigation pane, select "Users." 4. Check each user to ensure that
      MFA is enabled by looking for the "MFA device" column. 5. Alternatively, use
      the AWS CLI command aws iam list-virtual-mfa-devices to verify active MFA devices.
    Default Value: By default, IAM users are not required to have MFA enabled.
    Remediation: 1. Sign in to the AWS Management Console. 2. Navigate to the IAM
      service. 3. In the navigation pane, select "Users." 4. Choose the IAM user you
      want to enable MFA for. 5. Under the "Security credentials" tab, select "Manage
      MFA device." 6. Follow the prompts to assign and activate a virtual or hardware
      MFA device for the user.
