- rule:
  - ID: aps
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are configured to prevent
      public access. Publicly accessible buckets can lead to unauthorized data exposure.
    Rationale: Restricting public access to S3 buckets reduces the risk of sensitive
      data being exposed to unauthorized users. Publicly accessible buckets can be
      exploited, leading to data breaches and compliance violations.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select each bucket and review the "Permissions" tab.
    - Ensure that the "Block all public access" setting is enabled.
    - Verify that no bucket policies or access control lists (ACLs) allow public access.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation:
    - Enable "Block all public access" for each S3 bucket.
    - Review and update bucket policies and ACLs to remove public access permissions.
    - Use the AWS CLI or SDKs to automate the enforcement of these settings across
      all buckets.
