- rule:
    ID: aps
    Title: Ensure EC2 instances are not using default security groups
    Profile Applicability: Level 1
    Description: This check verifies that Amazon EC2 instances are not associated
      with the default security group. Default security groups typically allow all
      inbound traffic from the same security group, which can be a security risk.
    Rationale: Using default security groups can lead to unintended open access to
      EC2 instances, increasing the risk of unauthorized access and potential security
      breaches.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the EC2 Dashboard.
    - Select 'Instances' from the left-hand menu.
    - For each instance, check the associated security groups.
    - Verify that no instance is using the default security group.
    Default Value: By default, new EC2 instances may be associated with the default
      security group.
    Remediation:
    - Identify EC2 instances using the default security group.
    - Create a new security group with specific inbound and outbound rules that meet
      your security requirements.
    - Associate the new security group with the EC2 instances.
    - Remove the default security group association from the instances.
