- rule:
    ID: aps
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible.
      Public access to S3 buckets can lead to unauthorized access to sensitive data.
    Rationale: Publicly accessible S3 buckets can expose sensitive data to the internet,
      leading to data breaches and compliance violations. Ensuring buckets are not
      publicly accessible helps protect data integrity and confidentiality.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Check each bucket's permissions and ensure that they do not allow public access.
    - Use the AWS CLI command aws s3api get-bucket-acl to programmatically verify
      bucket permissions.
    Default Value: By default, new S3 buckets do not allow public access.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Go to the Permissions tab.
    - Disable any settings that allow public access.
    - Use the AWS CLI command aws s3api put-bucket-acl to update bucket permissions
      and remove public access.
