- rule:
  - ID: AWS-01
    Title: Ensure S3 Buckets are not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets do not allow public access
      to prevent unauthorized data exposure.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      data access. Ensuring buckets are private helps protect sensitive information.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket permissions for each S3 bucket.
    - Ensure that there are no public access permissions set.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation:
    - Go to the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Click on the 'Permissions' tab.
    - Ensure 'Block all public access' is enabled.
    - Remove any public access permissions from the bucket policy and access control
      list (ACL).
