- rule:
  - ID: AWS-001
  - Title: Ensure S3 Buckets are Not Publicly Accessible
  - Profile Applicability: Level 1
  - Description: This check ensures that Amazon S3 buckets do not allow public access.
      Publicly accessible S3 buckets can lead to data leaks if sensitive information
      is stored in them.
  - Rationale: Publicly accessible S3 buckets can be exploited by unauthorized users
      to access or modify sensitive data, leading to data breaches and compliance
      violations.
  - Audit: 1. Log in to the AWS Management Console. 2. Navigate to the S3 service.
      3. Select each bucket and click on the 'Permissions' tab. 4. Check the 'Block
      all public access' settings to ensure it is enabled. 5. Review the bucket policy
      and Access Control List (ACL) to confirm there are no public permissions.
  - Default Value: By default, S3 buckets block all public access unless explicitly
      configured otherwise.
  - Remediation: 1. Enable 'Block all public access' in the S3 bucket settings. 2.
      Remove any public access permissions from the bucket policy and ACL. 3. Regularly
      review and monitor bucket permissions to ensure compliance.
