- rule:
    ID: AWS-001
    Title: Enable Multi-Factor Authentication (MFA) for IAM Users
    Profile Applicability: Level 1, Level 2
    Description: Ensure that Multi-Factor Authentication (MFA) is enabled for all
      AWS Identity and Access Management (IAM) users. MFA adds an extra layer of security
      by requiring users to provide a second form of authentication, enhancing the
      protection of AWS accounts.
    Rationale: Enabling MFA for IAM users helps in preventing unauthorized access
      to AWS accounts. Without MFA, if a user's password is compromised, the account
      could be accessed and potentially misused. MFA significantly reduces the risk
      of unauthorized access.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Under 'Users', review each user to ensure that MFA is enabled.
    - For each user, check the 'Security Credentials' tab to verify MFA devices are
      assigned.
    Default Value: By default, IAM users do not have MFA enabled.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service and select the user for whom you want to enable
      MFA.
    - Go to the 'Security Credentials' tab and choose 'Manage MFA Device'.
    - Follow the steps to assign and activate an MFA device for the user.
