- rule:
  - ID: aps
    Title: Ensure S3 Buckets are Private
    Profile Applicability: Level 1
    Description: This check ensures that all S3 buckets are configured to be private,
      preventing unauthorized access to the data stored within them. Publicly accessible
      buckets can lead to data breaches and unauthorized data exposure.
    Rationale: Publicly accessible S3 buckets pose a significant security risk as
      they can expose sensitive data to the internet. Ensuring buckets are private
      reduces the risk of unauthorized access and data leaks.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket permissions for each bucket.
    - Ensure that no bucket is publicly accessible by checking the "Block Public Access"
      settings.
    Default Value: By default, S3 buckets are private unless explicitly made public.
    Remediation:
    - For each bucket that is not compliant, navigate to the S3 service in the AWS
      Management Console.
    - Select the bucket and go to the "Permissions" tab.
    - Enable "Block all public access" to ensure the bucket is private.
    - Review and update bucket policies and access control lists to restrict access
      to authorized users only.
