- rule:
    ID: AWS-BP-001
    Title: Ensure Multi-Factor Authentication (MFA) is enabled for all IAM users
    Profile Applicability: Level 1
    Description: This check ensures that Multi-Factor Authentication (MFA) is enabled
      for all AWS Identity and Access Management (IAM) users to enhance the security
      of user accounts. MFA adds an extra layer of protection on top of a username
      and password.
    Rationale: Enabling MFA for IAM users reduces the risk of unauthorized access
      to AWS accounts. Without MFA, if a password is compromised, an attacker can
      gain full access to the account, potentially leading to data breaches and unauthorized
      resource usage.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select 'Users' from the navigation pane.
    - For each user, verify that an MFA device is assigned under 'Security credentials'.
    - Alternatively, use the AWS CLI command aws iam list-virtual-mfa-devices to list
      users with assigned MFA devices and verify against the total list of users.
    Default Value: By default, IAM users do not have MFA enabled.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select 'Users' from the navigation pane.
    - Choose a user and select the 'Security credentials' tab.
    - Under 'Assigned MFA device', click 'Manage' and follow the steps to assign an
      MFA device to the user.
    - Repeat the process for all users without MFA.
