- rule:
    ID: app-integrations
    Title: Enable Multi-Factor Authentication (MFA) on the AWS Root Account
    Profile Applicability: Level 1, Level 2
    Description: Ensure that Multi-Factor Authentication (MFA) is enabled on the AWS
      root account. MFA adds an extra layer of protection on top of a password, requiring
      the user to provide a second form of verification.
    Rationale: The root account has unrestricted access to all resources in the AWS
      account. If compromised, it can lead to unauthorized access and potentially
      catastrophic changes to the account. MFA significantly reduces the risk of unauthorized
      access.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the IAM dashboard.
    - Select 'Users' and then 'root account'.
    - Check if MFA is enabled for the root account.
    Default Value: MFA not enabled by default on the root account.
    Remediation:
    - Log into the AWS Management Console with root account credentials.
    - Navigate to 'My Security Credentials'.
    - Under 'Multi-Factor Authentication', choose 'Activate MFA'.
    - Follow the instructions to enable MFA using a virtual MFA device, hardware device,
      or SMS.
