- rule:
    ID: AWS-BP-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that S3 buckets are not publicly accessible, which
      helps prevent unauthorized access to sensitive data stored in S3.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      access to sensitive information. Ensuring that buckets are not publicly accessible
      is a critical step in securing your data.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, review the bucket permissions.
    - Check the 'Block Public Access' settings and ensure that all public access is
      blocked.
    - Verify that bucket policies and access control lists (ACLs) do not allow public
      access.
    Default Value: By default, new S3 buckets have public access blocked.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Click on 'Permissions' and then 'Block public access'.
    - Enable all options to block public access.
    - Review and modify bucket policies and ACLs to ensure they do not allow public
      access.
