- rule:
  - ID: app-integrations
    Title: Ensure IAM Users Have MFA Enabled
    Profile Applicability: Level 1
    Description: This check ensures that all AWS IAM users have Multi-Factor Authentication
      (MFA) enabled. MFA adds an extra layer of security by requiring not only a password
      and username but also something that only the user has on them, i.e., a piece
      of information only they should know or have immediately to hand.
    Rationale: Enabling MFA for IAM users helps protect their accounts from unauthorized
      access. If MFA is not enabled, there is a higher risk of account compromise
      due to phishing attacks or password theft.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM dashboard.
    - In the navigation pane, choose Users.
    - For each user, check if the "MFA" column indicates that MFA is enabled.
    - Alternatively, use the AWS CLI command aws iam list-virtual-mfa-devices and
      check the output for users without MFA devices.
    Default Value: By default, IAM users are created without MFA enabled.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM dashboard.
    - In the navigation pane, choose Users.
    - Select a user and choose the "Security credentials" tab.
    - Under "Multi-factor Authentication (MFA)", choose "Manage" and then "Activate
      MFA".
    - Follow the prompts to enable MFA using a virtual MFA device or a hardware MFA
      device.
