- rule:
    ID: AWS-001
    Title: Ensure IAM Users Have MFA Enabled
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that all IAM users have multi-factor authentication
      (MFA) enabled to enhance account security. MFA adds an additional layer of security
      by requiring a second form of verification beyond just a password.
    Rationale: Enabling MFA for IAM users helps protect against unauthorized access
      in case user credentials are compromised. Without MFA, accounts are vulnerable
      to attacks that can lead to data breaches and unauthorized actions within the
      AWS environment.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select 'Users' from the navigation pane.
    - Check each user to confirm if MFA is enabled by looking under the 'MFA Device'
      column.
    Default Value: By default, MFA is not enabled for IAM users.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select 'Users' from the navigation pane.
    - Choose the user for whom you want to enable MFA.
    - Under 'Security credentials', select 'Manage MFA device'.
    - Follow the prompts to assign an MFA device to the user.
