- rule:
    ID: app-integrations
    Title: Ensure AWS S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible.
      Public access to S3 buckets can lead to data exposure and unauthorized access
      to sensitive information.
    Rationale: Publicly accessible S3 buckets can be exploited by malicious actors
      to access or manipulate data. Ensuring that buckets are private by default helps
      to protect sensitive data and maintain compliance with data privacy regulations.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket permissions and policies for each bucket.
    - Ensure that the "Block all public access" setting is enabled for each bucket.
    - Verify that there are no bucket policies or ACLs that allow public access.
    Default Value: By default, newly created S3 buckets do not allow public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the "Permissions" tab.
    - Enable the "Block all public access" option.
    - Review and update bucket policies and ACLs to remove any public access permissions.
