- rule:
    ID: app-integrations
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that S3 buckets do not allow public access. Public
      access can lead to data exposure and potential data breaches.
    Rationale: Publicly accessible S3 buckets can expose sensitive data to unauthorized
      users, leading to data leaks and compliance violations. Restricting access to
      trusted entities mitigates these risks.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the permissions for each bucket.
    - Ensure that no bucket policy or ACL grants public access.
    - Verify that the "Block Public Access" settings are enabled for the account and
      individual buckets.
    Default Value: By default, new S3 buckets do not allow public access.
    Remediation:
    - Use the AWS Management Console to review and modify bucket policies and ACLs
      to remove public access.
    - Enable "Block Public Access" settings for all S3 buckets and at the account
      level.
    - Regularly review bucket permissions to ensure compliance with security policies.
