- rule:
    ID: AWS-001
    Title: Enable Multi-Factor Authentication (MFA) for IAM Users
    Profile Applicability: Level 1, Level 2
    Description: Ensure that multi-factor authentication (MFA) is enabled for all
      IAM users to enhance the security of AWS accounts. MFA adds an extra layer of
      protection on top of a username and password by requiring a second form of authentication.
    Rationale: Enabling MFA for IAM users significantly reduces the risk of unauthorized
      access to AWS accounts. Without MFA, compromised credentials could lead to unauthorized
      access and potential data breaches.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the IAM service.
    - Select 'Users' from the navigation pane.
    - For each user, check the 'MFA' column to see if MFA is enabled.
    - Alternatively, use the AWS CLI command aws iam list-mfa-devices to list MFA
      devices associated with each IAM user.
    Default Value: By default, IAM users are created without MFA enabled.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the IAM service.
    - Select 'Users' from the navigation pane.
    - Click on the specific user for whom you want to enable MFA.
    - In the 'Security credentials' tab, choose 'Manage MFA device'.
    - Follow the prompts to enable and configure an MFA device for the user.
