- rule:
  - ID: application-autoscaling
    Title: Ensure Multi-Factor Authentication (MFA) is enabled for all IAM users
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Multi-Factor Authentication (MFA) is enabled
      for all AWS Identity and Access Management (IAM) users. MFA provides an additional
      layer of security by requiring users to provide a second form of authentication,
      thereby reducing the risk of unauthorized access to AWS resources.
    Rationale: Enabling MFA for IAM users significantly enhances the security of AWS
      accounts by requiring a second factor of authentication. Without MFA, accounts
      are more vulnerable to unauthorized access, which can lead to data breaches
      or misuse of resources.
    Audit: 1. Sign in to the AWS Management Console. 2. Navigate to the IAM dashboard.
      3. In the navigation pane, choose Users. 4. For each user, check the MFA column
      to verify if MFA is enabled. 5. Alternatively, use the AWS CLI command aws iam
      list-virtual-mfa-devices to list users without MFA.
    Default Value: By default, MFA is not enabled for IAM users.
    Remediation: 1. Sign in to the AWS Management Console. 2. Navigate to the IAM
      dashboard. 3. In the navigation pane, choose Users. 4. Select the user for whom
      you want to enable MFA. 5. Choose the Security credentials tab. 6. In the Multi-factor
      authentication section, choose Manage MFA device. 7. Follow the prompts to enable
      and configure MFA for the user.
