- rule:
    ID: application-autoscaling
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets do not have public access
      permissions. Publicly accessible S3 buckets can lead to data exposure and unauthorized
      access to sensitive information.
    Rationale: Public access to S3 buckets can result in data breaches and unauthorized
      access to sensitive data. It is crucial to restrict access to only authorized
      users to maintain data confidentiality and integrity.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the 'Permissions' tab.
    - Ensure that 'Block all public access' settings are enabled.
    - Verify that no bucket policies or ACLs allow public access.
    Default Value: By default, S3 buckets do not allow public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the 'Permissions' tab.
    - Enable 'Block all public access' settings.
    - Review and modify bucket policies and ACLs to restrict access to authorized
      users only.
