- rule:
  - ID: application-autoscaling
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that S3 buckets do not allow public read or write
      access. Publicly accessible buckets can expose sensitive data to the internet,
      leading to data breaches.
    Rationale: Restricting public access to S3 buckets minimizes the risk of unauthorized
      data exposure and potential data breaches. Public access can lead to sensitive
      data being exposed and misused.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket permissions and access control lists (ACLs) for each bucket.
    - Check the bucket policy to ensure it does not allow public access.
    - Use the AWS CLI command aws s3api get-bucket-acl to verify the access control
      list.
    - Use the AWS CLI command aws s3api get-bucket-policy to review the bucket policy.
    Default Value: By default, S3 buckets are private and not publicly accessible.
    Remediation:
    - If a bucket is found to be publicly accessible, modify the bucket's ACL to remove
      public access.
    - Update the bucket policy to restrict public access.
    - Use the AWS S3 Block Public Access feature to prevent future public access configurations.
