- rule:
  - ID: application-autoscaling
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check verifies that Amazon S3 buckets do not allow public access.
      Publicly accessible buckets can expose sensitive data and should be restricted
      to prevent unauthorized access.
    Rationale: Publicly accessible S3 buckets can lead to data breaches, unauthorized
      data access, and potential data loss. Ensuring buckets are private helps protect
      sensitive information and maintains compliance with data protection regulations.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Check the permissions of each bucket to ensure that public access is not allowed.
    - Use the AWS CLI command aws s3api get-bucket-acl to programmatically check the
      ACLs of each bucket.
    - Verify that the bucket policy does not grant public access by using the command
      aws s3api get-bucket-policy.
    Default Value: By default, new S3 buckets are private and do not allow public
      access.
    Remediation:
    - If a bucket is found to be publicly accessible, update the bucket's ACL and
      bucket policy to restrict access.
    - Use the AWS Management Console or the AWS CLI to remove any public access permissions.
    - Enable "Block Public Access" settings on the bucket to prevent future public
      access configurations.
