- rule:
  - ID: AWS-001
  - Title: Ensure S3 Buckets are not publicly accessible
  - Profile Applicability: Level 1
  - Description: This check ensures that all Amazon S3 buckets do not allow public
      access. Publicly accessible S3 buckets can lead to data exposure and unauthorized
      access to sensitive information.
  - Rationale: Public access to S3 buckets can result in data breaches and unauthorized
      data exposure. Ensuring buckets are not publicly accessible helps protect sensitive
      data and comply with security best practices.
  - Audit: 1. Log in to the AWS Management Console. 2. Navigate to the S3 service.
      3. For each bucket, check the "Block public access" settings. 4. Verify that
      the "Block all public access" option is enabled.
  - Default Value: By default, new S3 buckets have public access blocked.
  - Remediation: 1. Go to the AWS Management Console and open the S3 service. 2. Select
      the bucket that is publicly accessible. 3. Choose the "Permissions" tab. 4.
      Under "Block public access," click "Edit." 5. Enable "Block all public access"
      and save the changes.
