- rule:
  - ID: AWS-EC2-001
  - Title: Ensure EC2 Instances Are Using Approved AMIs
  - Profile Applicability: Level 1
  - Description: This check ensures that all EC2 instances are launched using AMIs
      that have been approved by the organization. Using approved AMIs helps maintain
      consistency, security, and compliance across the infrastructure.
  - Rationale: Approved AMIs are vetted for security and compliance standards. Using
      unapproved AMIs can introduce vulnerabilities, inconsistencies, and increase
      the risk of non-compliance with organizational policies.
  - Audit: 1. Log into the AWS Management Console. 2. Navigate to the EC2 Dashboard.
      3. List all running EC2 instances. 4. Verify the AMI ID of each instance against
      the list of approved AMIs maintained by the organization. 5. Identify any instances
      using non-approved AMIs.
  - Default Value: By default, EC2 instances can be launched with any public or private
      AMI unless restrictions are applied.
  - Remediation: 1. Identify instances running with non-approved AMIs. 2. Plan for
      a migration to an approved AMI, ensuring minimal disruption. 3. Create a new
      instance using an approved AMI. 4. Migrate necessary data and configurations
      to the new instance. 5. Terminate the non-compliant instance once the migration
      is complete. 6. Implement IAM policies or AWS Config rules to restrict the use
      of unapproved AMIs in the future.
