- rule:
  - ID: AWS-S3-01
  - Title: Ensure S3 Buckets are Not Publicly Accessible
  - Profile Applicability: Level 1
  - Description: This check ensures that Amazon S3 buckets are not publicly accessible,
      which helps prevent unauthorized access to sensitive data stored in S3.
  - Rationale: Publicly accessible S3 buckets can lead to data breaches, as unauthorized
      users may access, modify, or delete sensitive data. Ensuring buckets are private
      protects data integrity and confidentiality.
  - Audit: 1. Log in to the AWS Management Console. 2. Navigate to the S3 service.
      3. Review the permissions for each bucket. 4. Ensure that bucket policies and
      access control lists (ACLs) do not allow public access. 5. Use the AWS CLI command
      aws s3api get-bucket-acl --bucket <bucket-name> to check ACL settings. 6. Use
      the AWS CLI command aws s3api get-bucket-policy --bucket <bucket-name> to review
      bucket policies.
  - Default Value: By default, new S3 buckets are private and do not allow public
      access.
  - Remediation: 1. If a bucket is found to be publicly accessible, remove any public
      access permissions from the bucket policy and ACL. 2. Apply a bucket policy
      that denies public access. 3. Use AWS S3 Block Public Access settings to prevent
      public access at the account and bucket level.
