- rule:
    ID: AWS-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: Check to ensure that S3 buckets do not allow public access to prevent
      unauthorized data exposure.
    Rationale: Publicly accessible S3 buckets can lead to sensitive data exposure,
      data breaches, and compliance violations. Restricting access to authenticated
      users minimizes these risks.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket you want to audit.
    - Check the bucket permissions and access control list (ACL) settings to ensure
      'Block all public access' is enabled.
    Default Value: By default, new S3 buckets do not allow public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the 'Permissions' tab.
    - Enable 'Block all public access' to restrict unauthorized access.
