- rule:
  - ID: application-autoscaling
  - Title: Ensure IAM Password Policy is Enabled
  - Profile Applicability: Level 1
  - Description: This check ensures that an IAM password policy is enabled to enforce
      strong password requirements for IAM users. A robust password policy helps protect
      AWS resources by requiring users to create complex passwords that are difficult
      to guess.
  - Rationale: Enforcing a strong password policy reduces the risk of unauthorized
      access to AWS resources by ensuring that passwords are not easily compromised.
      Without a strong password policy, users might create weak passwords, increasing
      the risk of account breaches.
  - Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - In the navigation pane, choose 'Account settings'.
    - Verify that 'Password policy' is enabled and configured with appropriate settings,
      such as minimum password length, requiring numbers, symbols, and uppercase letters.
  - Default Value: By default, IAM does not enforce a password policy.
  - Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - In the navigation pane, choose 'Account settings'.
    - Enable 'Password policy' and configure it to require strong passwords, including
      minimum length, requiring numbers, symbols, and uppercase letters.
    - Save the changes to enforce the password policy for all IAM users.
