- rule:
    ID: AWS-S3-001
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets do not have public access
      permissions that could expose sensitive data. Public access can lead to unauthorized
      data exposure and potential data breaches.
    Rationale: Publicly accessible S3 buckets can lead to unauthorized access and
      data breaches. Ensuring that buckets are not publicly accessible helps to protect
      sensitive data and comply with security best practices.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select each bucket and review the permissions tab.
    - Check for any public access settings and evaluate bucket policies and ACLs for
      public access.
    - Use the AWS CLI command aws s3api get-bucket-policy-status --bucket <bucket-name>
      to verify the policy status.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Review and modify the bucket policy and ACL to remove public access.
    - Consider enabling block public access settings for the bucket.
    - Verify the changes by checking the bucket access permissions again.
