- rule:
    ID: AWS-001
    Title: Ensure Multi-Factor Authentication (MFA) is enabled for all IAM users
    Profile Applicability: Level 1
    Description: This security check verifies that all AWS Identity and Access Management
      (IAM) users have Multi-Factor Authentication (MFA) enabled. MFA adds an extra
      layer of security by requiring not only a password and username but also something
      that only the user has on them, i.e., a physical token or device.
    Rationale: Enabling MFA for IAM users significantly reduces the risk of compromised
      accounts. Without MFA, if a user's password is exposed, an attacker can gain
      full access to the user's permissions. MFA mitigates this risk by requiring
      an additional authentication factor.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM dashboard.
    - In the left navigation pane, choose Users.
    - For each user, check the MFA column to verify that MFA is enabled.
    Default Value: By default, MFA is not enabled for IAM users.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM dashboard.
    - In the left navigation pane, choose Users.
    - Select the user for whom you want to enable MFA.
    - Choose the Security credentials tab.
    - In the Multi-factor Authentication (MFA) section, choose Manage.
    - Follow the prompts to enable MFA for the user.
