- rule:
  - ID: AWS-001
    Title: Ensure Multi-Factor Authentication (MFA) is enabled for all IAM users
    Profile Applicability: Level 1
    Description: Enabling Multi-Factor Authentication (MFA) for all IAM users adds
      an additional layer of security by requiring a second form of verification during
      the sign-in process. This helps protect user accounts from unauthorized access.
    Rationale: MFA significantly reduces the risk of compromised accounts by requiring
      a second factor of authentication. Without MFA, accounts are more vulnerable
      to attacks such as phishing, password guessing, and credential theft.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select 'Users' from the navigation pane.
    - For each user, check the 'Security Credentials' tab to verify if MFA is enabled.
    - Alternatively, use the AWS CLI command aws iam list-mfa-devices to list MFA
      devices for each user.
    Default Value: By default, IAM users are not required to use MFA.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select 'Users' from the navigation pane.
    - Choose the user for whom you want to enable MFA.
    - Go to the 'Security Credentials' tab and click on 'Manage' under 'Multi-factor
      Authentication (MFA)'.
    - Follow the prompts to assign and activate an MFA device for the user.
