- rule:
  - ID: config
    Title: Ensure AWS S3 Buckets are not publicly accessible
    Profile Applicability: Level 1
    Description: This check ensures that AWS S3 buckets are configured to prevent
      public access. Publicly accessible buckets can lead to data leaks and unauthorized
      access to sensitive information.
    Rationale: Publicly accessible S3 buckets can expose sensitive data to the internet,
      leading to data breaches and compliance violations. Ensuring buckets are private
      by default mitigates these risks.
    Audit: 1. Log in to the AWS Management Console. 2. Navigate to the S3 service.
      3. Select a bucket and click on the "Permissions" tab. 4. Check the "Block public
      access" settings to ensure that public access is blocked. 5. Verify that there
      are no bucket policies allowing public access.
    Default Value: By default, S3 buckets do not block public access.
    Remediation: 1. Go to the AWS Management Console and open the S3 service. 2. Select
      the bucket needing remediation. 3. Click on the "Permissions" tab. 4. Enable
      "Block all public access" under the "Block public access" settings. 5. Review
      and remove any bucket policies or ACLs that grant public access.
