- rule:
  - ID: AWS-001
    Title: Ensure S3 Buckets are Private
    Profile Applicability: Level 1
    Description: This check ensures that all Amazon S3 buckets are configured to be
      private, preventing unauthorized access to sensitive data.
    Rationale: Keeping S3 buckets private protects against unauthorized data access
      and potential data breaches, which could lead to financial loss and reputational
      damage.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the bucket permissions and ensure that the bucket policy
      does not allow public access.
    - Verify that the "Block Public Access" settings are enabled for all buckets.
    Default Value: By default, S3 buckets are private when created, but access settings
      can be modified.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Update the bucket policy to restrict public access.
    - Enable "Block Public Access" settings for the bucket.
