- rule:
    ID: config
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets are not publicly accessible
      to prevent unauthorized access to sensitive data. Publicly accessible buckets
      can expose sensitive information to the internet, leading to data breaches.
    Rationale: By ensuring that S3 buckets are not publicly accessible, you mitigate
      the risk of unauthorized access to your data. Public access can lead to data
      leaks, compliance violations, and financial losses.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the bucket permissions to ensure there is no public access.
    - Verify the bucket policy and access control lists (ACLs) to ensure they do not
      grant public access.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to review
      ACL settings.
    - Use the AWS CLI command aws s3api get-bucket-policy --bucket <bucket-name> to
      review bucket policy.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation:
    - Remove any public access permissions from the bucket ACLs and policies.
    - Implement bucket policies that restrict access to specific users or roles.
    - Enable bucket logging to monitor access requests.
    - Use the AWS S3 Block Public Access feature to prevent public access settings
      on new and existing buckets.
