- rule:
    ID: config
    Title: Ensure S3 Buckets Are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that S3 buckets are not publicly accessible unless
      explicitly required. Publicly accessible buckets can lead to data leaks and
      unauthorized access to sensitive information.
    Rationale: Publicly accessible S3 buckets can expose data to the internet, leading
      to potential data breaches and unauthorized access. Ensuring buckets are private
      by default reduces the risk of accidental data exposure.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the 'Permissions' tab.
    - Ensure that the bucket policy does not grant public access.
    - Verify that 'Block all public access' settings are enabled.
    Default Value: By default, newly created S3 buckets are private.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the 'Permissions' tab and review the bucket policy.
    - Modify the bucket policy to restrict public access.
    - Enable 'Block all public access' settings for the bucket.
