- rule:
  - ID: AWS-EC2-001
    Title: Ensure EC2 instances are not using default security groups
    Profile Applicability: Level 1
    Description: EC2 instances should not be associated with the default security
      group, which allows all inbound and outbound traffic. Ensuring instances use
      custom security groups helps enforce more granular access control.
    Rationale: Using the default security group poses a security risk as it allows
      unrestricted access. Custom security groups can enforce the principle of least
      privilege, reducing the attack surface.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the EC2 dashboard.
    - Select Instances from the left-hand menu.
    - For each instance, check the associated security groups.
    - Verify that none of the instances are using the default security group.
    Default Value: By default, EC2 instances may be launched with the default security
      group if not specified otherwise.
    Remediation:
    - Identify instances using the default security group.
    - Create a new security group with specific inbound and outbound rules.
    - Associate the new security group with the instances.
    - Remove the default security group association from the instances.
