- rule:
    ID: AWS-001
    Title: Enable Multi-Factor Authentication (MFA) for All IAM Users
    Profile Applicability: Level 1
    Description: Ensure that Multi-Factor Authentication (MFA) is enabled for all
      IAM users to add an extra layer of security. MFA requires users to provide two
      or more verification factors to gain access to AWS, reducing the risk of compromised
      accounts.
    Rationale: Enabling MFA enhances security by requiring additional verification,
      which helps protect accounts from unauthorized access due to compromised passwords.
      Without MFA, accounts are more vulnerable to attacks, potentially leading to
      unauthorized access and data breaches.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the IAM service.
    - Check the "Users" section to review each user's security status.
    - Verify that MFA is enabled for each user. This can be confirmed if the "MFA
      Device" column shows a device assigned.
    Default Value: By default, MFA is not enabled for IAM users.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the IAM service.
    - Select the user for whom you want to enable MFA.
    - Under the "Security credentials" tab, choose "Manage" next to "Assigned MFA
      device".
    - Follow the prompts to assign and activate an MFA device for the user.
