- rule:
    ID: config
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets do not have public access
      permissions that could lead to unauthorized data exposure. Publicly accessible
      buckets can be accessed by anyone on the internet, posing a significant security
      risk.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      access to sensitive information. Ensuring that buckets are not publicly accessible
      helps protect data integrity and confidentiality.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket permissions for each bucket.
    - Check the 'Block Public Access' settings to ensure they are enabled.
    - Verify that no bucket policies or ACLs allow public access.
    Default Value: By default, new S3 buckets have all public access blocked.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Click on 'Permissions' and then 'Block public access'.
    - Enable all four options to block public access.
    - Review and modify any bucket policies or ACLs that grant public access.
