- rule:
  - ID: mgn
    Title: Ensure Multi-Factor Authentication (MFA) is enabled for all IAM users
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that MFA is enabled for all AWS IAM users to enhance
      account security by requiring a second form of authentication.
    Rationale: Enabling MFA reduces the risk of compromised credentials, as it requires
      an additional verification step beyond username and password. Without MFA, accounts
      are more vulnerable to unauthorized access, which can lead to data breaches
      and other security incidents.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM dashboard.
    - Select "Users" from the navigation pane.
    - For each user, check the "MFA" column to verify if MFA is enabled.
    - Alternatively, use the AWS CLI command aws iam list-users and aws iam get-user
      to programmatically check MFA status for each user.
    Default Value: MFA is not enabled by default for IAM users.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM dashboard and select "Users."
    - Click on each user and choose "Security credentials."
    - Under "Assigned MFA device," click "Manage" and follow the steps to assign an
      MFA device.
    - Ensure all users complete the MFA setup process.
