- rule:
  - ID: mgn
  - Title: Ensure EC2 Instances are not using default security groups
  - Profile Applicability: Level 1
  - Description: This check ensures that EC2 instances are not associated with the
      default security group. Default security groups allow all inbound traffic by
      default, which can pose a security risk.
  - Rationale: Using the default security group for EC2 instances can lead to unintended
      open access to instances, increasing the risk of unauthorized access and potential
      exploitation. By ensuring instances are associated with custom security groups,
      you can enforce specific inbound and outbound rules that align with security
      best practices.
  - Audit: 1. Log in to the AWS Management Console. 2. Navigate to the EC2 Dashboard.
      3. Select 'Instances' from the left panel. 4. For each instance, check the security
      groups associated with it. 5. Verify that none of the instances are using the
      default security group.
  - Default Value: By default, EC2 instances may be associated with the default security
      group if no other group is specified.
  - Remediation: 1. Identify EC2 instances using the default security group. 2. Create
      a new security group with specific inbound and outbound rules as per your security
      requirements. 3. Detach the default security group from the instances. 4. Attach
      the newly created security group to the instances.
