- rule:
  - ID: mgn
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1, Level 2
    Description: This check verifies that Amazon S3 buckets are not publicly accessible
      to prevent unauthorized access to sensitive data. Public access to S3 buckets
      can lead to data breaches and exposure of confidential information.
    Rationale: Publicly accessible S3 buckets can be exploited by attackers to access,
      modify, or delete sensitive data. Ensuring that S3 buckets are not publicly
      accessible reduces the risk of data leaks and unauthorized access.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the bucket permissions and ensure that the bucket policy
      and access control list (ACL) do not allow public access.
    - Use the S3 Block Public Access feature to ensure that no public access is allowed.
    Default Value: By default, new S3 buckets do not allow public access.
    Remediation:
    - Review and modify the bucket policy and ACL to remove any public access permissions.
    - Enable the S3 Block Public Access feature for the bucket to prevent future public
      access configurations.
    - Regularly audit S3 bucket permissions to ensure compliance with security best
      practices.
