- rule:
  - ID: AWS-S3-01
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible,
      which could lead to unauthorized data access.
    Rationale: Publicly accessible S3 buckets can expose sensitive data to the internet,
      leading to data breaches and compliance violations. Ensuring buckets are private
      mitigates these risks.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select each bucket and review the permissions tab.
    - Verify that the bucket does not allow public access.
    - Alternatively, use the AWS CLI command: aws s3api get-bucket-acl --bucket <bucket-name>
        to check the ACL settings.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the permissions tab and edit the bucket policy and ACL to restrict public
      access.
    - Use the Block Public Access settings to prevent future public access configurations.
