- rule:
  - ID: AWS-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets are not publicly accessible
      to prevent unauthorized data access. Public access to S3 buckets can lead to
      data breaches and exposure of sensitive information.
    Rationale: Publicly accessible S3 buckets can be exploited by malicious actors
      to access, modify, or delete data. Restricting access to only authorized users
      and applications minimizes the risk of data leaks and unauthorized modifications.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the permissions tab to ensure that the bucket is not
      publicly accessible.
    - Verify that there are no bucket policies or ACLs that allow public access.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to review
      the bucket's ACL settings.
    - Use the AWS CLI command aws s3api get-bucket-policy --bucket <bucket-name> to
      review the bucket's policy settings.
    Default Value: By default, new S3 buckets are private and not publicly accessible.
    Remediation:
    - Remove any public access permissions from the bucket policy and ACL.
    - Enable S3 Block Public Access settings for the account and individual buckets.
    - Use IAM policies to grant access only to specific users or applications that
      require it.
