- rule:
  - ID: mgn
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: Ensure that Amazon S3 buckets do not allow public access to prevent
      unauthorized data exposure. This is crucial for maintaining the confidentiality
      and integrity of the data stored in S3.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      access to sensitive information. Limiting access to only necessary users and
      services helps protect data from exposure and potential misuse.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the bucket permissions and ensure that the bucket policy
      does not allow public access.
    - Verify that the block public access settings are enabled for each bucket.
    Default Value: By default, new S3 buckets do not allow public access unless explicitly
      configured.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Review and update the bucket policy to remove any public access permissions.
    - Enable block public access settings for the bucket to prevent future public
      access.
