- rule:
  - ID: mgn
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets are not publicly accessible
      unless explicitly required. Publicly accessible buckets can expose sensitive
      data to the internet, leading to potential data breaches.
    Rationale: Restricting public access to S3 buckets mitigates the risk of unauthorized
      data exposure. Public buckets can be accessed by anyone on the internet, which
      can lead to data leakage and compliance violations.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Review the permissions of each bucket under the "Permissions" tab.
    - Ensure that the "Block all public access" setting is enabled for each bucket.
    - Verify that there are no bucket policies or access control lists (ACLs) that
      grant public access.
    Default Value: By default, new S3 buckets have all public access blocked.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Go to the "Permissions" tab and enable the "Block all public access" setting.
    - Review and update bucket policies and ACLs to remove any public access permissions.
