- rule:
  - ID: AWS-S3-01
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible,
      which could lead to unauthorized data access and potential data breaches.
    Rationale: Publicly accessible S3 buckets can expose sensitive data to unauthorized
      users, leading to data leaks and compliance violations. Ensuring buckets are
      private helps maintain data security and integrity.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket permissions and policies for each S3 bucket.
    - Ensure that no bucket has public read or write access.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to verify
      permissions.
    Default Value: By default, new S3 buckets are private and do not allow public
      access.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Go to the Permissions tab.
    - Remove any public access settings or policies that grant public access.
    - Use the Block Public Access feature to prevent future public access configurations.
