- rule:
    ID: mgn
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets do not allow public access.
      Publicly accessible buckets can expose sensitive data to unauthorized users,
      leading to data breaches.
    Rationale: Restricting public access to S3 buckets is essential to protect sensitive
      data from unauthorized access and potential data leaks. Publicly accessible
      buckets can be exploited by attackers to gain access to confidential information.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket you want to audit.
    - Go to the Permissions tab.
    - Check the Block all public access settings to ensure they are enabled.
    - Review the bucket policy and access control list (ACL) to ensure no public access
      is granted.
    Default Value: By default, new S3 buckets have all public access blocked.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Go to the Permissions tab.
    - Enable the Block all public access settings.
    - Review and modify the bucket policy and ACL to remove any public access permissions.
