- rule:
  - ID: mgn
    Title: Ensure S3 Buckets are not publicly accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets are not publicly accessible,
      which could lead to unauthorized access and data breaches.
    Rationale: Publicly accessible S3 buckets can expose sensitive data to the internet,
      leading to potential data leaks and security incidents. It is crucial to restrict
      access to only those who need it.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - For each S3 bucket, check the permissions tab.
    - Verify that the bucket does not have public access enabled.
    - Alternatively, use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name>
      to review the bucket's ACL for public access permissions.
    Default Value: By default, Amazon S3 buckets are private and not publicly accessible.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that needs to be secured.
    - Go to the permissions tab and disable any public access settings.
    - Review and adjust the bucket policy and ACL to ensure no public access is granted.
    - Use AWS Identity and Access Management (IAM) policies to control access to the
      bucket.
