- rule:
  - ID: application-cost-profiler
  - Title: Ensure EC2 Instances Are Not Using Default Security Groups
  - Profile Applicability: Level 1
  - Description: EC2 instances should not be associated with the default security
      group. Default security groups allow all inbound traffic, which can pose a significant
      security risk.
  - Rationale: Using the default security group can lead to exposure of instances
      to the internet, increasing the risk of unauthorized access. Custom security
      groups with restricted access should be used to enhance security.
  - Audit: 1. Log in to the AWS Management Console. 2. Navigate to the EC2 dashboard.
      3. Select 'Instances' from the sidebar. 4. For each instance, check the associated
      security groups. 5. Verify that no instances are using the default security
      group.
  - Default Value: By default, EC2 instances may use the default security group if
      no other group is specified.
  - Remediation: 1. Identify instances using the default security group. 2. Create
      a new security group with appropriate rules. 3. Associate the new security group
      with the instances. 4. Remove the default security group from the instances.
