- rule:
  - ID: application-cost-profiler
    Title: Ensure S3 Buckets are Private
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are configured to be private,
      preventing unauthorized access to sensitive data stored within the buckets.
    Rationale: Keeping S3 buckets private is crucial to prevent unauthorized access
      to sensitive data. Publicly accessible buckets can lead to data breaches and
      unauthorized data exposure.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select each bucket and review the "Permissions" tab.
    - Ensure that the bucket policy and access control list (ACL) do not allow public
      access.
    - Verify that the "Block all public access" setting is enabled.
    Default Value: By default, new S3 buckets are private and do not allow public
      access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is not compliant.
    - Go to the "Permissions" tab and modify the bucket policy and ACL to restrict
      public access.
    - Enable the "Block all public access" setting to ensure the bucket remains private.
