- rule:
  - ID: application-cost-profiler
  - Title: Ensure EC2 instances are not using the default security group
  - Profile Applicability: Level 1
  - Description: Check that EC2 instances are not associated with the default security
      group, which allows unrestricted inbound traffic. This is crucial for maintaining
      a secure AWS environment.
  - Rationale: Using the default security group poses a security risk as it allows
      unrestricted access to EC2 instances. This can lead to unauthorized access and
      potential data breaches.
  - Audit: 1. Log in to the AWS Management Console. 2. Navigate to the EC2 dashboard.
      3. Select 'Instances' from the left-hand menu. 4. For each instance, check the
      associated security groups. 5. Verify that none of the instances are using the
      default security group.
  - Default Value: By default, new EC2 instances may be associated with the default
      security group, which allows all inbound traffic.
  - Remediation: 1. Create a new security group with specific inbound rules tailored
      to your application needs. 2. Disassociate the default security group from the
      EC2 instances. 3. Associate the newly created security group with the EC2 instances.
