- rule:
  - ID: application-cost-profiler
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets do not allow public access.
      Publicly accessible buckets can expose sensitive data to unauthorized users,
      leading to data breaches.
    Rationale: Restricting public access to S3 buckets minimizes the risk of unauthorized
      data exposure. Publicly accessible buckets can be a target for data theft or
      accidental data leaks.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the "Permissions" tab.
    - Ensure that the bucket policy and access control list (ACL) do not grant public
      access.
    Default Value: By default, S3 buckets are private, and public access is not enabled.
    Remediation:
    - Remove any public access permissions from the bucket policy and ACL.
    - Use the AWS S3 Block Public Access feature to restrict public access to the
      bucket.
    - Regularly review bucket permissions to ensure compliance with security policies.
