- rule:
  - ID: AWS-001
    Title: Enable Multi-Factor Authentication (MFA) for All IAM Users
    Profile Applicability: Level 1, Level 2
    Description: Ensure that all AWS Identity and Access Management (IAM) users have
      Multi-Factor Authentication (MFA) enabled to add an extra layer of security
      to user accounts. MFA requires users to provide two or more verification factors
      to gain access to AWS resources, significantly reducing the risk of unauthorized
      access.
    Rationale: Enabling MFA for IAM users helps protect against unauthorized access
      to AWS accounts. Without MFA, compromised credentials can lead to unauthorized
      access and potential data breaches, resulting in financial and reputational
      damage.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM dashboard.
    - Select "Users" from the navigation pane.
    - For each user, check the "MFA" column to verify that MFA is enabled.
    Default Value: By default, MFA is not enabled for IAM users.
    Remediation:
    - Log in to the AWS Management Console.
    - Go to the IAM dashboard and select "Users."
    - Click on a user name to view its details.
    - Under the "Security credentials" tab, click "Manage MFA device."
    - Follow the prompts to assign and activate an MFA device for the user.
