- rule:
  - ID: AWS-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets do not have public read
      or write access. Publicly accessible buckets can lead to data exposure and unauthorized
      access.
    Rationale: Publicly accessible S3 buckets pose a significant security risk as
      they can lead to unauthorized access to sensitive data, data breaches, and compliance
      violations.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the 'Permissions' tab.
    - Verify that there are no public access settings enabled.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> and
      ensure no 'AllUsers' or 'AuthenticatedUsers' groups have access.
    Default Value: By default, new S3 buckets are private and do not allow public
      access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Go to the 'Permissions' tab and review the 'Block Public Access' settings.
    - Ensure 'Block all public access' is enabled.
    - Remove any bucket policies or access control lists (ACLs) that grant public
      access.
