- rule:
    ID: AWS-001
    Title: Enable Multi-Factor Authentication (MFA) for AWS Root Account
    Profile Applicability: Level 1
    Description: Ensure that Multi-Factor Authentication (MFA) is enabled for the
      AWS root account to add an extra layer of security. MFA requires users to present
      two or more separate forms of authentication, enhancing the security of the
      root account.
    Rationale: Enabling MFA helps protect the root account from unauthorized access.
      The root account has unrestricted access to all resources in the AWS account,
      and if compromised, can lead to severe security breaches and data loss. MFA
      adds an additional security measure beyond just a password.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select the "Dashboard" option.
    - Check the "Security Status" section to verify if MFA is enabled for the root
      account.
    Default Value: By default, MFA is not enabled for the AWS root account.
    Remediation:
    - Log in to the AWS Management Console with your root account credentials.
    - Navigate to the IAM service.
    - Select the "Dashboard" option.
    - In the "Security Status" section, click on "Activate MFA on your root account."
    - Follow the prompts to enable MFA using a virtual MFA device or a hardware MFA
      device.
