- rule:
    ID: AWS-001
    Title: Ensure IAM Users Have MFA Enabled
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that all IAM users in your AWS account have multi-factor
      authentication (MFA) enabled. MFA provides an additional layer of security by
      requiring users to present two or more separate forms of identification before
      gaining access to AWS resources.
    Rationale: Enabling MFA for IAM users reduces the risk of compromised credentials
      being used to access your AWS account. Without MFA, a malicious actor with access
      to a user's password could gain unauthorized access to your resources, potentially
      leading to data breaches or service disruptions.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - In the navigation pane, choose Users.
    - For each user, check the "MFA Device" column to verify if MFA is enabled.
    - Alternatively, use the AWS CLI command aws iam list-virtual-mfa-devices to list
      users without MFA.
    Default Value: By default, IAM users do not have MFA enabled.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the IAM service.
    - Select the user for whom you want to enable MFA.
    - Choose the "Security credentials" tab.
    - Under "Assigned MFA device," choose "Manage" and follow the steps to assign
      an MFA device to the user.
