- rule:
    ID: AWS-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that all Amazon S3 buckets do not allow public
      access. Publicly accessible S3 buckets can expose sensitive data to unauthorized
      users, leading to potential data breaches.
    Rationale: Publicly accessible S3 buckets pose a significant security risk as
      they can be accessed by anyone on the internet. This can lead to unauthorized
      data access, data leaks, and compliance violations.
    Audit: 1. Log in to the AWS Management Console. 2. Navigate to the S3 service.
      3. For each bucket, check the bucket permissions and ensure that 'Block all
      public access' is enabled. 4. Use the AWS CLI command aws s3api get-bucket-policy-status
      --bucket <bucket-name> to verify the public access settings.
    Default Value: By default, new S3 buckets block all public access.
    Remediation: 1. Go to the S3 console in the AWS Management Console. 2. Select
      the bucket that is publicly accessible. 3. Click on the 'Permissions' tab. 4.
      Under 'Block public access (bucket settings)', click 'Edit'. 5. Enable 'Block
      all public access' and save changes.
