- rule:
  - ID: AWS-S3-001
  - Title: Ensure S3 Buckets are Private by Default
  - Profile Applicability: Level 1
  - Description: This check ensures that all Amazon S3 buckets are set to private
      by default, preventing unauthorized access to the data stored within them. S3
      buckets should not be publicly accessible unless explicitly required.
  - Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      access to sensitive information. Ensuring buckets are private by default minimizes
      the risk of exposing data inadvertently.
  - Audit: 1. Log in to the AWS Management Console. 2. Navigate to the S3 service.
      3. For each bucket, check the permissions tab to ensure that the bucket policy
      and ACLs do not allow public access. 4. Use the AWS CLI command aws s3api get-bucket-acl
      --bucket <bucket-name> to verify that the ACL does not grant public access.
      5. Use the AWS CLI command aws s3api get-bucket-policy --bucket <bucket-name>
      to ensure the bucket policy does not allow public access.
  - Default Value: By default, new S3 buckets are private and do not allow public
      access.
  - Remediation: 1. If a bucket is found to be publicly accessible, review the bucket
      policy and ACL settings. 2. Remove any statements in the bucket policy or ACL
      that grant public access. 3. Implement bucket policies that explicitly deny
      public access unless required for specific use cases. 4. Utilize AWS S3 Block
      Public Access settings to prevent public access at the account level.
