- rule:
    ID: apptest
    Title: Ensure S3 buckets are not publicly accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets do not have public access
      to prevent unauthorized access to sensitive data. Public access can lead to
      data breaches and exposure of confidential information.
    Rationale: Publicly accessible S3 buckets can expose sensitive data to the internet,
      leading to potential data leaks and security breaches. Ensuring buckets are
      not publicly accessible helps maintain data privacy and integrity.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket list and click on each bucket.
    - Check the bucket's permissions under the "Permissions" tab.
    - Verify that the "Block public access" settings are enabled.
    - Confirm that no bucket policies or access control lists (ACLs) allow public
      access.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Go to the "Permissions" tab.
    - Enable "Block all public access" settings.
    - Review and modify any bucket policies or ACLs that allow public access.
