- rule:
  - ID: AWS-S3-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: Check to ensure that Amazon S3 buckets do not allow public access.
      Publicly accessible buckets can expose sensitive data to unauthorized users.
      This check helps to ensure that data stored in S3 buckets is protected from
      unauthorized access.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      data exposure, posing a significant security risk. Ensuring that buckets are
      not publicly accessible helps to protect sensitive information from being exposed
      to the internet.
    Audit:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - For each bucket, check the bucket permissions and ensure that the "Block all
      public access" setting is enabled.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket <bucket-name> to verify
      that no public access permissions are granted.
    Default Value: By default, S3 buckets are private and do not allow public access.
    Remediation:
    - Log into the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Click on "Permissions" and then "Block public access."
    - Ensure that the "Block all public access" option is checked and save the changes.
    - Review and remove any bucket policies or ACLs that grant public access.
