- rule:
    ID: AWS-001
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1
    Description: This check ensures that Amazon S3 buckets are not publicly accessible
      to prevent unauthorized access and data breaches.
    Rationale: Publicly accessible S3 buckets can lead to data exposure and unauthorized
      access, posing significant security risks and potential compliance violations.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket permissions and policies for each bucket.
    - Ensure that no bucket has public access permissions.
    Default Value: By default, S3 buckets are private and not publicly accessible.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket that is publicly accessible.
    - Click on the "Permissions" tab.
    - Edit the bucket policy and remove any public access permissions.
    - Save the changes to ensure the bucket is no longer publicly accessible.
