- rule:
    ID: apptest
    Title: Enable Versioning for S3 Buckets
    Profile Applicability: Level 1
    Description: Ensure that versioning is enabled for all S3 buckets to protect against
      accidental or malicious deletion or overwriting of objects.
    Rationale: Enabling versioning in S3 buckets provides protection against unintended
      overwrites and deletions by maintaining a history of object versions. This is
      crucial for data recovery and maintaining data integrity.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select each bucket and check the "Properties" tab.
    - Verify that "Versioning" is listed as "Enabled" for each bucket.
    Default Value: Versioning is not enabled by default on S3 buckets.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select the bucket where versioning needs to be enabled.
    - Go to the "Properties" tab and click on "Versioning".
    - Click "Enable" and save the changes.
