- rule:
    ID: apptest
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: Ensure that your Amazon S3 buckets do not allow public access unless
      explicitly required. Publicly accessible buckets can lead to unauthorized data
      exposure and should be avoided to maintain data confidentiality.
    Rationale: Publicly accessible S3 buckets pose a significant security risk as
      they can expose sensitive data to the internet. This exposure can lead to data
      breaches, unauthorized data manipulation, and compliance violations. Restricting
      public access helps secure data and ensures compliance with data protection
      standards.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the list of buckets and check the 'Access' column to identify buckets
      with public access.
    - For each bucket, click on the bucket name and go to the 'Permissions' tab.
    - Verify that the 'Block public access' settings are enabled.
    - Check the bucket policy and access control list (ACL) to ensure no public permissions
      are granted.
    Default Value: By default, new S3 buckets block all public access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service and select the bucket.
    - Go to the 'Permissions' tab and enable 'Block all public access'.
    - Review and modify the bucket policy and ACL to remove any public permissions.
    - Save the changes to ensure the bucket is not publicly accessible.
