- rule:
    ID: AWS-EC2-001
    Title: Ensure EC2 instances are not using default security groups
    Profile Applicability: Level 1
    Description: This check ensures that EC2 instances are not associated with the
      default security group. The default security group allows unrestricted inbound
      and outbound traffic, which can pose security risks.
    Rationale: Using the default security group can expose your instances to unnecessary
      risks as it allows all inbound and outbound traffic. Restricting access through
      customized security groups improves the security posture by limiting access
      to only necessary ports and IPs.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the EC2 dashboard.
    - Select 'Instances' from the menu.
    - For each instance, check the 'Security groups' column.
    - Verify that no instance is associated with the default security group.
    Default Value: By default, EC2 instances may be associated with the default security
      group unless specified otherwise.
    Remediation:
    - Identify the instances using the default security group.
    - Create a new security group with the necessary inbound and outbound rules.
    - Detach the default security group from the instances.
    - Attach the newly created security group to the instances.
