- rule:
  - ID: apptest
    Title: Ensure S3 Buckets are not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that Amazon S3 buckets do not allow public access
      unless explicitly required. Publicly accessible buckets can lead to unintended
      data exposure.
    Rationale: Publicly accessible S3 buckets can lead to data breaches and unauthorized
      access to sensitive information. Ensuring buckets are private by default reduces
      the risk of data exposure.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Review the bucket permissions to ensure that 'Block all public access' is enabled.
    - Use the AWS CLI command aws s3api get-bucket-acl --bucket BUCKET_NAME to check
      the ACL settings.
    - Use the AWS CLI command aws s3api get-bucket-policy --bucket BUCKET_NAME to
      review the bucket policy for public access statements.
    Default Value: By default, new S3 buckets are private and do not allow public
      access.
    Remediation:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service and select the affected bucket.
    - Click on 'Permissions' and ensure 'Block all public access' is enabled.
    - Remove any bucket policies or ACLs that allow public access.
    - Re-evaluate the need for public access and apply the least privilege principle.
