- rule:
    ID: apptest
    Title: Ensure S3 Buckets are Not Publicly Accessible
    Profile Applicability: Level 1, Level 2
    Description: This check ensures that all Amazon S3 buckets are configured to prevent
      public access. Publicly accessible S3 buckets can lead to data breaches if sensitive
      information is inadvertently exposed.
    Rationale: Publicly accessible S3 buckets pose a security risk as they can expose
      sensitive data to unauthorized users. Ensuring that buckets are not publicly
      accessible reduces the risk of data leaks and unauthorized access.
    Audit:
    - Log in to the AWS Management Console.
    - Navigate to the S3 service.
    - Select a bucket and go to the 'Permissions' tab.
    - Check the 'Block public access' settings to ensure all options are enabled.
    - Verify that there are no bucket policies or access control lists (ACLs) that
      allow public access.
    Default Value: By default, new S3 buckets block all public access.
    Remediation:
    - Enable 'Block all public access' on the S3 bucket settings.
    - Review and update bucket policies and ACLs to ensure they do not allow public
      access.
    - Regularly audit S3 bucket permissions to maintain compliance.
